[package]
name = "lattix-py"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "lattix"
crate-type = ["cdylib"]
doc = false

[dependencies]
lattix-core = { path = "../lattix-core", features = ["algo", "formats"] }
pyo3 = { version = "0.20", features = ["extension-module"] }
